import type { Metadata } from "next";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

// Metadata الخاص بالموقع
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// نعرف نوع البراميتر بدل استخدام LayoutProps من next
type Props = {
  children: React.ReactNode;
  params: { locale: "ar" | "en" };
};

export default async function LocaleLayout({ children, params }: Props) {
  const { locale } = params;

  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages({ locale });

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
